// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtKeCaKj9gvMyigV-K9g_VoxpPgtesXY4',
    appId: '1:419047799354:web:6064c550f07047acfc9303',
    messagingSenderId: '419047799354',
    projectId: 'edward-sflutterproject',
    authDomain: 'edward-sflutterproject.firebaseapp.com',
    storageBucket: 'edward-sflutterproject.firebasestorage.app',
    measurementId: 'G-X98BBBTPHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMpbD51J-7lUJmoXtk7X23DMSJsbYkptU',
    appId: '1:419047799354:android:1fbf9fd345516f3efc9303',
    messagingSenderId: '419047799354',
    projectId: 'edward-sflutterproject',
    storageBucket: 'edward-sflutterproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmde4vJD4Ec4iGxnoTFDYOxx8r3seb1mM',
    appId: '1:419047799354:ios:d40e7a6db21bcbacfc9303',
    messagingSenderId: '419047799354',
    projectId: 'edward-sflutterproject',
    storageBucket: 'edward-sflutterproject.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmde4vJD4Ec4iGxnoTFDYOxx8r3seb1mM',
    appId: '1:419047799354:ios:d40e7a6db21bcbacfc9303',
    messagingSenderId: '419047799354',
    projectId: 'edward-sflutterproject',
    storageBucket: 'edward-sflutterproject.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtKeCaKj9gvMyigV-K9g_VoxpPgtesXY4',
    appId: '1:419047799354:web:b2c006101bc24187fc9303',
    messagingSenderId: '419047799354',
    projectId: 'edward-sflutterproject',
    authDomain: 'edward-sflutterproject.firebaseapp.com',
    storageBucket: 'edward-sflutterproject.firebasestorage.app',
    measurementId: 'G-86SZLJJYEW',
  );
}
